// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zltisyxdtrbxbwhhgxyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsdGlzeXhkdHJieGJ3aGhneHlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc2NTA4NDgsImV4cCI6MjA5MzIyNjg0OH0.lAwqzTMj5o5bDb54VzCDw3mu5Z5u7li91ALFBSwmzlU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);